# Generated by Django 5.1.7 on 2025-03-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '留言板', 'verbose_name_plural': '留言板'},
        ),
    ]
