# Generated by Django 5.1.7 on 2025-03-21 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='标题')),
                ('introduce', models.CharField(blank=True, max_length=100, verbose_name='描述')),
                ('photo', models.ImageField(blank=True, upload_to='image/', verbose_name='图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '图片信息',
                'verbose_name_plural': '图片信息',
                'db_table': 'album_info',
            },
        ),
    ]
